language: python

python:
  - 3.6
  - 3.7

cache:
  apt: true
  directories:
    - $HOME/.cache/pip
    - $HOME/downloads

install: skip
script: ./ci/test.sh ${TRAVIS_PYTHON_VERSION}

env:
  global:
    - CIBW_BUILD: cp36-* cp37-*
    - CIBW_BEFORE_BUILD: pip install cython

jobs:
  include:

  - stage: pypi
    install: pip install cibuildwheel==0.12.0
    script: cibuildwheel --output-dir wheelhouse
    deploy:
      provider: pypi
      user: MaxHalford
      password:
        secure: IKlAIBIeaM6muU5ITEM5a6BwYwDzRI5Bn30ssnS9oRRTLEqsU70Ih+2eWX5UbascgBTdtMJLdE9vEsp4F6TLNgdjmZPyYXZLb6hTDu0lz5PeFiJ4EHVNyC7PqjDpPWiU9kE1lXMAfbDADIWnK/bNvgfn5xlbUfTPnnMd1bsazJtYSOumoYpjhvEPRkC/A/+iVHfBXFvt4UqXVZw/HgcZfBze8heLGh3klAyO6QuIIbfXvf9Oiym8BnfnaPKvJi+npmitL7wMtTP/Oq/zFg0RQdBPZhcqvnwJ5c1XQDWbLJArs56IqPEk/eN3HpvDbo+bZD1Lc3ACA71bCkKDTnkhZ+0uVga9rQaue/dCQ8l+PIIHwfesv8Wb5sTA3YGaHhTFcN645AAttlvN/GHluJNuufdnp2HrTicCnsXM+9HvgvQgdNB4xVOGuinAebMyEoX6pi99dUNZXl7knFr8VTfu4YKstH59pz7PDAq5FYLpPOxpgc1+nKa0DSCj7VMKZy4G+PDbok+LKtNJj1BCKwdZFb0QQUNLLQYJfvFLJfEcArYHLb+fNgtOT87IB4TnQD2O3vNkTx7Z3/oSMaLqfIP9Jwc1q8YlLvNp7u3L04ar0V09p9xnW3qoMzWTImPZimNOjabPE6Ieoyu6N7FJsPEwAsW3S4GeSZertcy1HJLhTkU=
      on:
        all_branches: true
      skip_existing: true
    if: tag IS present

  - stage: docs
    install:
      - sudo apt-get install graphviz pandoc
      - pip install cython
      - python setup.py install
      - pip install -e ".[docs]"
      - pytest --nbval-lax --current-env docs/notebooks/*.ipynb
    script: make doc
    after_success:
      - git config --global user.email "maxhalford25@gmail.com"
      - git config --global user.name "MaxHalford"
      - git config --global push.default matching
      - git clone https://${GH_TOKEN}@github.com/creme-ml/creme-ml.github.io.git creme-ml.github.io
      - cd creme-ml.github.io
      - rm -r *
      - cp -r ../docs/_build/html/* .
      - cp -r ../docs/_build/html/.* .
      - git add -A
      - git commit --allow-empty -m "Travis build number $TRAVIS_BUILD_NUMBER"
      - git push --set-upstream origin master
    if: tag IS present

env:
  global:
    secure: diU7M/lZeRtnN1cpb9nSBwtyflzmKTsB5rp3T0lgwNI24egwSITSidvMON+D1DNTHaxE/JCHpWMFvU+ivBIrBcmYZeO7tqijj3FrKPQxMZ1GiI0l7c5ifIdO0FmxjdzkzfLdlJs2wm/PuhEf9ckkMR265BpLBsfmL3/JnFu5mEKVzs5ai15Ky7ushnkhX28Bv89It+UOfD7R3zQk50a7c+8B+BkHe72mf9kJsvD9Qi8keiogGezw+eYbxcjbh13vq4YQzbaBm8eux93Zt3pfTwQZff7iX89RbwtrM7p1jFTv34tMJyyp8EJIicwhTy1PQvoPMUvSzrCajJIGCboy/FLZgbscj6monbohTlSEtpTaq9sJsfn1GB4ofST0OVTdj6pW8aztYrDPA8zXGNV+Cy7k4y7sk4V0QLLC8A2nTn7X/63GCIFn7aezwWi6JmZMuG+54qJqpb7sV5vrsUrJ5SV3W5T/9+qek5BnVbzb+WO0a4FHuJidvpxHi3Jl4VlwUVzjmuKVrjHoO7Z8Dxm2WvoK68LZtZsDUeyh1NX5qHp1Br/PX1I52xAEQiyGqM8JQy0S62I3NkmP/EJ1W3Px3yj7KIE+WuY+SyQmuzKo2ad0p8sYWIWfRtwJBerc0b5wQ8hXM0yCWwh6ZAebPMb6TexgDvfUbzPL1HSP7vDoQ9s=
