# Project information
site_name: creme
site_description: A Material Design theme for MkDocs
site_author: The creme developers
site_url: https://creme-ml.github.io/

# Repository
repo_name: creme-ml/creme
repo_url: https://github.com/creme-ml/creme

# Copyright
copyright: Copyright &copy; 2019 - 2020

# Configuration
theme:
    name: material
    custom_dir: docs/overrides
    language: en
    palette:
        primary: indigo
        accent: indigo
    font:
        text: Roboto
        code: Roboto Mono
    logo: img/creme_square.svg
    favicon: img/favicon.ico
    features:
        - navigation.tabs
        - navigation.instant

# Extras
extra:
    social:
      - icon: fontawesome/brands/github-alt
        link: https://github.com/creme-ml/creme

# Google Analytics
google_analytics:
  - UA-63302552-3
  - auto

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
        guess_lang: false
  - footnotes
  - toc:
        permalink: true
        toc_depth: "1-3"
  - pymdownx.details
  - pymdownx.arithmatex

plugins:
  - search
  - awesome-pages

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

  - js/version-select.js
extra_css:
  - stylesheets/extra.css
  - css/version-select.css
