[build-system]
requires = ["poetry-core>=1.0.0", "cython", "numpy", "setuptools", "wheel", "setuptools-rust"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "river"
version = "0.20.1"
description = "Online machine learning in Python"
readme = "README.md"
homepage = "https://riverml.xyz/"
repository = "https://github.com/online-ml/river/"
authors = ["Max Halford <maxhalford25@gmail.com>"]

[tool.poetry.build]
generate-setup-file = true
script = "build.py"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
scipy = "^1.8.1"
pandas = "^2.1"

[tool.poetry.group.dev.dependencies]
black = "^23.10.0"
graphviz = "^0.20.1"
gym = "^0.26.2"
matplotlib = "^3.0.2"
mypy = "^1.6.1"
pre-commit = "^3.5.0"
pytest = "^7.4.2"
ruff = "^0.1.1"
scikit-learn = "^1.3.1"
sqlalchemy = "^2.0.22"
sympy = "^1.10.1"
pytest-xdist = {extras = ["psutil"], version = "^3.3.1"}
ipykernel = "^6.26.0"
ipython = "^8.17.2"
rich = "^13.6.0"
jupyter = "^1.0.0"
mike = "^2.0.0"

[tool.poetry.group.compat]
optional = true

[tool.poetry.group.compat.dependencies]
scikit-learn = "^1.0.1"
sqlalchemy = "^2.0.0"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
"dominate" = "*"
"flask" = "*"
"ipykernel" = "*"
"jupyter-client" = "*"
"mike" = "*"
"mkdocs" = "*"
"mkdocs-awesome-pages-plugin" = "*"
"mkdocs-charts-plugin" = "*"
"mkdocs-material" = "*"
"nbconvert" = "*"
"numpydoc" = "*"
"python-slugify" = "*"
"spacy" = "*"
"tabulate" = "*"
"watermark" = "*"

[tool.poetry.group.benchmark]
optional = true

[tool.poetry.group.benchmark.dependencies]
"dominate" = "2.8.0"
"scikit-learn" = "1.3.1"
"scipy" = "1.11.3"
"tabulate" = "0.9.0"
"vowpalwabbit" = "9.9.0"
"watermark" = "2.4.3"

[tool.pytest.ini_options]
addopts = [
    "--doctest-modules",
    "--doctest-glob=README.md",
    "--ignore=build.py",
    "--ignore=benchmarks",
    "--ignore=docs/scripts",
    "--verbose",
    "-ra",
    "-m not datasets and not slow",
    "--color=yes",
]
doctest_optionflags = "NORMALIZE_WHITESPACE NUMBER ELLIPSIS"
norecursedirs = [
    "build",
    "docs",
    "node_modules",
    ".eggs",
    "scikit-multiflow",
    "site",
    "benchmarks",
]
markers = [
    "datasets: tests that pertain to the datasets module",
    "slow: tests that take a long time to run",
]

[tool.black]
line-length = 100
target-version = ['py310']

[tool.ruff]
select = ["E", "F", "I", "UP"]  # https://beta.ruff.rs/docs/rules/
line-length = 100
target-version = 'py310'
ignore = ["E501"]

[tool.ruff.isort]
required-imports = ["from __future__ import annotations"]

[tool.mypy]
files = "river"

[[tool.mypy.overrides]]
module = [
    "river.*",
    "mmh3.*",
    "numpy.*",
    "sklearn.*",
    "pytest.*",
    "pandas.*",
    "scipy.*",
    "graphviz.*",
    "vaex.*",
    "torch.*",
    "sqlalchemy.*",
    "requests.*"
]
ignore_missing_imports = true
