name: river-benchmarks
channels:
  - conda-forge
  - defaults
dependencies:
  - boost=1.78.0
  - boost-cpp=1.78.0
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - cython=0.29.32
  - eigen=3.4.0
  - fmt=9.1.0
  - icu=70.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=14.0.6
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libopenblas=0.3.21
  - libsqlite=3.39.4
  - libzlib=1.2.13
  - llvm-openmp=14.0.4
  - ncurses=6.3
  - numba=0.56.3
  - numpy=1.23.4
  - openssl=3.0.5
  - pip=22.3
  - python=3.9.7
  - python_abi=3.9
  - rapidjson=1.1.0
  - readline=8.1.2
  - setuptools=65.5.0
  - spdlog=1.10.0
  - sqlite=3.39.4
  - tk=8.6.12
  - vowpalwabbit=9.5.0
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - enum-compat==0.0.3
    - llvmlite==0.39.1
    - markupsafe==2.1.1
    # - onelearn==0.3.0
    - packaging==21.3
    - param==1.12.2
    - pillow==9.2.0
    - pyct==0.4.8
    - pyrsistent==0.18.1
    - pytz-deprecation-shim==0.1.0.post0
    - pyyaml==6.0
    - scikit-learn==1.1.2
    - scipy==1.9.3
    - toml==0.10.2
    - toolz==0.12.0
    - torch==1.12.1
    - tornado==5.1.1
    - tzdata==2022.5
    - watchdog==2.1.9
