name: release-docs

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          # Use 3.12 for the docs env waiting for spaCy and srsly to support 3.13
          python-version: "3.12"

      - name: Install Ubuntu dependencies
        run: sudo apt-get install graphviz pandoc

      - name: Install dependencies
        run: |
          uv run --group docs python -m spacy download en_core_web_sm

      - name: Use Rich in notebooks
        run: |
          uv run --group docs ipython profile create
          echo "%load_ext rich" > ~/.ipython/profile_default/startup/00_rich.ipy

      - name: Execute notebooks
        run: uv run --group docs make execute-notebooks

      - name: Build docs
        run: uv run --group docs make doc

      - name: Deploy docs
        env:
          GH_TOKEN: ${{ secrets.GitHubToken }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config pull.rebase false
          git add --all
          git commit -m "Execute notebooks"
          git fetch
          git checkout gh-pages
          git pull
          git checkout main
          RIVER_VERSION=$(uv run --group docs python -c "import river; print(river.__version__)")
          uv run --group docs mike deploy ${RIVER_VERSION} latest --update-aliases --push --remote https://${GH_TOKEN}@github.com/online-ml/river.git
