name: unit-tests

on:
  push:
    branches:
      - main
      - feature/dep_cache

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: [3.8, 3.9, "3.10"]
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: set up rust
        if: matrix.os != 'ubuntu-latest'
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=nightly --profile=minimal -y && rustup show
        if: matrix.os == 'ubuntu-latest'

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Cache the Python environment
        uses: actions/cache@v2
        id: cache-venv
        with:
          path: ~/.venv
          key: ${{ runner.os }}-${{ matrix.python }}-venv-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python }}-venv-

      - name: Install Python dependencies
        if: ${{ steps.cache-venv.outputs.cache-hit != 'true' }}
        run: |
          python -m pip install --upgrade pip
          python -m venv ~/.venv
          source ~/.venv/bin/activate
          pip install scikit-learn sqlalchemy
          pip install pytest-xdist[psutil]

      - name: Build River
        run: |
          source ~/.venv/bin/activate
          pip install -e ".[dev]"

      - name: Cache River datasets
        uses: actions/cache@v2
        with:
          path: ~/river_data
          key: ${{ runner.os }}

      - name: Cache scikit-learn datasets
        uses: actions/cache@v2
        with:
          path: ~/scikit_learn_data
          key: ${{ runner.os }}

      - name: Download datasets
        run: |
          source ~/.venv/bin/activate
          python -c "from river import datasets; datasets.CreditCard().download(); datasets.Elec2().download()"

      - name: pytest
        run: |
          source ~/.venv/bin/activate
          pytest -m "not datasets" --durations=10 -n logical # Run pytest on all logical CPU cores